### DISCUSSION TITLE
How to setup a config with a PI motor_stage [for confocal microscopy]

### DISCUSSION THREAD

**Discussion by mario-b-amaro** [Ulm-IQO/qudi-iqo-modules#104] [Q&A] [answered]
This might be a very simple question, but I can't seem to figure it out. I might be making some confusion, as well. Thank you in advance for the help!

I have a setup with a PI P-541.2 XY Piezo Stage and a PI P-721, which gives me control over the three axis. They are connected to three PI E-621 on a PI 501 modular controller. I have tested them using COM ports and it is all working fine, so then I decided to try them from Qudi.

It seems that there are already written modules for these devices (motor_stage_pi?), but I can't seem to figure out where or how they would appear in a config file. I tried to use the default.cfg as a reference, but the motor_dummy is not used there. Does someone have an example config file for some setup they've made using these devices (or similar)?

**Comment by NicolasStaudenmaier** [comment]
Hi @mario-b-amaro, 

all modules should have an example config in their documentation. Check the description directly under the class `MotorStagePI`. To configure the hardware you have to write the configuration in your .cfg file under the "hardware" section. The example configuration for the PI motor stage is: 

```
Example config for copy-paste:

    motorstage_pi:
        module.Class: 'motor.motor_stage_pi.MotorStagePI'
        options:
            com_port_pi_xyz: 'ASRL1::INSTR'
            pi_xyz_baud_rate: 9600
            pi_xyz_timeout: 1000
            pi_xyz_term_char: '\n'
            pi_first_axis_label: 'x'
            pi_second_axis_label: 'y'
            pi_third_axis_label: 'z'
            pi_first_axis_ID: '1'
            pi_second_axis_ID: '2'
            pi_third_axis_ID: '3'

            pi_first_min: -0.1 # in m
            pi_first_max: 0.1 # in m
            pi_second_min: -0.1 # in m
            pi_second_max: 0.1 # in m
            pi_third_min: -0.1 # in m
            pi_third_max: 0.1 # in m

            pi_first_axis_step: 1e-7 # in m
            pi_second_axis_step: 1e-7 # in m
            pi_third_axis_step: 1e-7 # in m

            vel_first_min: 1e-5 # in m/s
            vel_first_max: 5e-2 # in m/s
            vel_second_min: 1e-5 # in m/s
            vel_second_max: 5e-2 # in m/s
            vel_third_min: 1e-5 # in m/s
            vel_third_max: 5e-2 # in m/s

            vel_first_axis_step: 1e-5 # in m/s
            vel_second_axis_step: 1e-5 # in m/s
            vel_third_axis_step: 1e-5 # in m/s
```
